global:
  scrape_interval:     15s
  evaluation_interval: 30s

rule_files:
  - my-rules.yaml'

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
  - job_name: api
    metrics_path: /custom-metrics-path
    scrape_timeout: 10s
    static_configs:
      - targets: ['api-1.course-go.dev:8080', 'api-2.course-go.dev:8080']
    authorization:
      type: Bearer
      credentials_file: /etc/prometheus/api.jwt
