# // START OMIT

name: Go
on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.54

# // LINT OMIT

  build:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: go build -v ./...

  test:
    needs: build
    runs-on: ubuntu-latest
    steps: 
      - name: Test
        run: go test -race -cover -coverprofile coverage.out ./...

      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: Test coverage
          path: coverage.out

# // TEST OMIT

  docker:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PAT }}

      - name: Login to GitHub Packages
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup buildx
        uses: docker/setup-buildx-action@v3

# // DOCKER SETUP OMIT

      - name: Gather image metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ vars.DOCKERHUB_NAMESPACE }}/${{ vars.DOCKERHUB_REPOSITORY }}
            ghcr.io/${{ github.repository }}
          tags: latest

      - name: Build and push the image
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/amd64, linux/arm64, linux/arm64/v8
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

# // DOCKER PUSH OMIT
