FROM --platform=$BUILDPLATFORM golang:1.25-alpine AS build

WORKDIR /usr/app
COPY . .
ARG TARGETOS TARGETARCH

RUN GOOS=$TARGETOS GOARCH=$TARGETARCH go build -v -o /usr/app/bin/app .


FROM alpine:3

COPY --from=build /usr/app/bin/app /bin

ENTRYPOINT [ "app" ]
